### ISSUE TITLE
Lithium or Bat% vs. BatV

### ISSUE THREAD

**Issue by Gisbert1** [bagges/deye-esp32-bridge#15]
Hi Bagges,

in your code deye-esp32-bridge.yaml, the BatV mode is commented out.
NEEDED IF YOU USE BatV%
NEEDED IF YOU USE Lithium or Bat%
Do I need to make a decision before I flash the code to the ESP32 or can I use both in the code at the same time? Of course not in the Deye - there is only one mode at one time possible.

I have a second question:
Currently I have no battery and later I will have a battery with a JKBMS which will not have any data communication to the Deye or your board - but I still want to use your board and your code. Can I simply delete any parts of the code with is related to "bms" or "seplos", ...? For the Deye the modbus_id is modbus1. Can I have a modbus_id modbus1 and no modbus0 or do I need to start always with modbus0?

I would be great if you could publish a version deye-esp32-bridge-batv.yaml (no BMS but charging mode BatV in the Deye menu).

Best Regards
Gisbert

**Comment by bagges** [comment]
You can add both to the code before you flash the ESP32 but I do not know what happens if you change values when different mode is choosen in the inverter.

You can just delete everything. But you could also add those configuration: https://github.com/syssi/esphome-jk-bms/ and crimp an adapter to fit the pinout of the jkbms.

modbus0, modbus1,... it's just a name. can be anything.
